### ISSUE TITLE
make correlation between wikipedia list of reservoirs and CDEC station ID's

### ISSUE THREAD

**Issue by adynata** [adynata/The-CA-Reservoir-Review#1]
Add column to wikipedia sourced spreadsheet with the three letter station code from the CDEC tables

https://docs.google.com/spreadsheets/d/1yewYTYELrqSv8KFoQ6ouldcKkFW2B0h13oHbvUSWAt0/edit?usp=sharing

https://docs.google.com/spreadsheets/d/1KodKszlPy28V-3EljjrMfIJcyh7UMG2S_kxOjqfUsoU/edit?usp=sharing

possible way to bring in data from google drive to rails backend:
http://stackoverflow.com/questions/30331510/access-a-google-drive-spreadsheet-in-ruby-on-rails

**Comment by kbryerman** [comment]
I've added three letter station codes to the wikipedia sourced spreadsheet, Column "I". There were a few stations that weren't listed and I've highlighted them in yellow; 24 reservoirs are included in both spreadsheets.
